### ISSUE TITLE
Capture daily facility open/closed status on metrics objects.

### ISSUE THREAD

**Issue by kgorana** [bcgov/parks-reso-api#309]
## Description

When a BC Parks admin user exports the capacity report it can show that 350 passes are available on all days even when the season is over and the facility is set to closed. It would be useful to have the report show 0 passes available when the facility is closed as that reflects reality. This ticket is to do that automatically instead of having a user go in and adjust any capacity numbers, the capacity numbers should stay the same but when a facility is closed it shows as no passes available. 

This ticket is to add status properties to our metrics schema.

When a new metrics object is created, it should include the status of the facility, which can be gathered from resObjs for past/future dates, and from the facility itself for current dates if no resObj exists.

```
{
  pk: metrics::<orcs>::<facilityName>,
  sk:<shortDate>,
  ...
  status: 'open' || 'closed',
}
```

There is also an opportunity here to collect information on whether the facility had passes required or not on a given day. Open/closed status and `Booking Days` & `Bookable Holidays` have different definitions. It should be investigated whether `Passes Required` can also be captured on a metrics object - though this is not captured in resObjs so it may not be possible.

```
passesRequired: true || false
```

For example, a facility may not have any bookings because it is open but not requiring passes.

## Acceptance Criteria

* Facility `status` is included in the `metrics` object when it is created
* Facility `Passes Required` is investigated on whether it can be included in the metrics object, and if it can be included, `Passes Required` is included in the metrics object when it is created
* Relevant exporters reflect the status/passRequired of the facility (if applicable)

## Notes

Exporters such as the capacity exporter may need updates to show the new status information.

## Linked issues

blocks
- [ ] https://github.com/bcgov/parks-reso-admin/issues/312

relates to
- [x] ~[BRS-1020](https://bcparksdigital.atlassian.net/browse/BRS-1020)~

**Comment by cameronpettit** [comment]
Addressed in https://github.com/bcgov/parks-reso-api/pull/341 and https://github.com/bcgov/parks-reso-admin/pull/330

**Comment by manuji** [comment]
Tested on TEST: **Pending**
* Verified that the capacity report now has two columns for "Status" and "Passes required".
* But, when the Status is set to Close, the Passes required still show TRUE (here as per the description i assume it should show FALSE: Need to clarify this @JLWade ). Also, if the Status is closed do you want the individual capacities for AM, PM, and All day to show zero?

**Comment by JLWade** [comment]
When status is set to closed, passes can still be required as this may be due to a snowstorm or one of many is closed so technically passes are still required by the facility itself is closed or unaccessible.
If the capacity report has those two columns visible now that should work for offline analysis - I will need to confirm with marshall for longer term changes to that chart in the admin tool.

**Comment by manuji** [comment]
Thanks for the reply @JLWade . I will then move this to PO review.

**Comment by JLWade** [comment]
@cameronpettit do yo uknow what the N/A means? looking at joffre in test


![Image](https://github.com/bcgov/parks-reso-api/assets/38668130/228e5b53-f865-40da-a630-ac4cfd393524)

**Comment by cameronpettit** [comment]
This only hit TEST 4 days ago. Only net new metrics will have a status attribute.

**Comment by JLWade** [comment]
thought that might be the case - moving to done
